apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 79.5.0
      helm:
        releaseName: kube-prometheus-stack
        values: |
          grafana:
            enabled: true
            adminPassword: project-nexus-grafana
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 256Mi

          prometheus:
            prometheusSpec:
              retention: 7d
              resources:
                requests:
                  cpu: 200m
                  memory: 512Mi
                limits:
                  cpu: 1000m
                  memory: 1Gi

          alertmanager:
            enabled: true
            alertmanagerSpec:
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 256Mi

          kubeStateMetrics:
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi

          prometheusOperator:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 256Mi

            admissionWebhooks:
              patch:
                resources:
                  requests:
                    cpu: 50m
                    memory: 32Mi
                  limits:
                    cpu: 200m
                    memory: 128Mi

          nodeExporter:
            resources:
              requests:
                cpu: 50m
                memory: 32Mi
              limits:
                cpu: 200m
                memory: 64Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true