apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-nexus
  namespace: project-nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-nexus
  template:
    metadata:
      labels:
        app: project-nexus
    spec:
      containers:
        - name: project-nexus
          image: image: localhost:5000/project-nexus:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "dev"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10