apiVersion: v1
kind: Service
metadata:
  name: project-nexus
  namespace: project-nexus
spec:
  selector:
    app: project-nexus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP